# Generated by Django 3.2.4 on 2021-07-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(max_length=10)),
                ('subjectname', models.CharField(max_length=250)),
                ('pdf', models.FileField(upload_to='pdfs')),
                ('video', models.URLField()),
            ],
        ),
    ]
